development: &development
  adapter: postgresql
  encoding: unicode
  database: oedo_rukaigi03_development
  pool: 5
  username: postgres
  password:
  min_messages: warning

test: &test
  <<: *development
  database: oedo_rubykaigi03_test
